import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useParams } from 'react-router-dom';

export default function ItemReader() {
  const { t, i18n } = useTranslation();
  const [translatedText, setTranslatedText] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [playbackSpeed, setPlaybackSpeed] = useState(1);
  const { id } = useParams();
  const [item, setItem] = useState<any>(null);
  const [summary, setSummary] = useState<any>(null);
  const [zoom, setZoom] = useState(100);

  const handleTranslate = async () => {
    if (i18n.language === 'en') { setTranslatedText(null); return; }
    const res = await fetch(`http://localhost:8000/api/items/${id}/translate?target=${i18n.language}`);
    const data = await res.json();
    setTranslatedText(data.translated_text);
  };

  const handleTTS = async () => {
    if (isPlaying) { setIsPlaying(false); return; }
    setIsPlaying(true);
    await fetch(`http://localhost:8000/api/items/${id}/tts?lang=${i18n.language}`);
  };

  useEffect(() => {
    handleTranslate();
  }, [i18n.language]);

  useEffect(() => {
    // Fetch item details
    fetch(`http://localhost:8000/api/items/${id}`)
      .then(res => res.json())
      .then(data => setItem(data));
      
    // Fetch AI Summary
    fetch(`http://localhost:8000/api/items/${id}/summary`)
      .then(res => res.json())
      .then(data => setSummary(data));
  }, [id]);

  if (!item) return <div className="p-8 text-white">Loading document...</div>;
  if (item.error) return <div className="p-8 text-white">Document not found.</div>;

  return (
    <div className="min-h-screen flex flex-col" style={{ background: 'var(--color-suit-navy)', color: 'var(--color-paper)', fontFamily: 'var(--font-sans)' }}>
      {/* Top Toolbar */}
      <div className="flex justify-between items-center p-4 bg-black bg-opacity-40 border-b border-white border-opacity-10">
        <div>
          <h1 className="text-xl font-bold" style={{ fontFamily: 'var(--font-serif)', color: 'var(--color-gold)' }}>{item.title}</h1>
          <p className="text-xs opacity-60">{item.creator} • {item.date}</p>
        </div>
        <div className="flex gap-4 items-center">
          <div className="flex bg-white bg-opacity-10 rounded overflow-hidden">
            <button onClick={() => setZoom(z => Math.max(50, z - 10))} className="px-3 py-1 hover:bg-white hover:bg-opacity-20">-</button>
            <span className="px-3 py-1 text-sm border-x border-white border-opacity-10">{zoom}%</span>
            <button onClick={() => setZoom(z => Math.min(200, z + 10))} className="px-3 py-1 hover:bg-white hover:bg-opacity-20">+</button>
          </div>

          <button onClick={handleTTS} className={`px-4 py-1.5 text-sm border rounded transition-colors ${isPlaying ? 'bg-red-500 text-white border-red-500' : 'border-yellow-500 text-yellow-500 hover:bg-yellow-500 hover:text-black'}`}>
            {isPlaying ? 'Stop Audio' : t('Listen')}
          </button>
          <button className="px-4 py-1.5 text-sm border border-yellow-500 text-yellow-500 rounded hover:bg-yellow-500 hover:text-black transition-colors">
            Cite (APA)
          </button>
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Left: Document Viewer (Mock) */}
        <div className="flex-1 overflow-auto p-8 flex justify-center items-start bg-gray-900 bg-opacity-50">
           <div 
             className="bg-white text-black p-12 shadow-2xl transition-transform origin-top" 
             style={{ width: '800px', minHeight: '1100px', transform: `scale(${zoom / 100})`, fontFamily: 'var(--font-serif)' }}
           >
             <div className="text-center mb-12">
               <h2 className="text-3xl font-bold mb-4">{item.title}</h2>
               <p className="italic text-gray-600">{item.creator}</p>
             </div>
             
             <div className="text-lg leading-loose space-y-6 text-gray-800">
               {translatedText && (
                 <div className="bg-yellow-50 p-4 border-l-4 border-yellow-500 mb-6 rounded-r">
                   <span className="text-xs font-bold text-yellow-700 uppercase block mb-2">Machine Translated ({i18n.language})</span>
                   {translatedText}
                 </div>
               )}
               <p>[Page Image / OCR Synced Text Layer Placeholder]</p>
               <p>{item.description}</p>
               <p>This is a simulated reader view. In the final version, this will render high-resolution zoomable tiles (IIIF/OpenSeadragon) overlaid with transparent selectable text blocks generated by Tesseract.</p>
             </div>
           </div>
        </div>

        {/* Right: AI Summary & Metadata */}
        <div className="w-96 bg-black bg-opacity-20 border-l border-white border-opacity-10 overflow-y-auto p-6">
          <h3 className="text-lg font-bold mb-4 border-b border-white border-opacity-10 pb-2" style={{ color: 'var(--color-gold)' }}>AI Summary</h3>
          
          {summary ? (
            <div className="space-y-4 mb-8">
              <div className="bg-blue-900 bg-opacity-20 border border-blue-500 border-opacity-30 p-3 rounded-lg text-sm text-blue-200">
                <span className="font-bold block mb-1">Quick Take</span>
                {summary.short_summary}
              </div>
              <div className="text-sm opacity-80 leading-relaxed">
                {summary.detailed_summary}
              </div>
              <div className="text-xs text-green-400 opacity-70 border border-green-800 bg-green-900 bg-opacity-20 inline-block px-2 py-1 rounded">
                Status: {summary.status.replace(/_/g, ' ')}
              </div>
            </div>
          ) : (
            <div className="animate-pulse mb-8">Generating summary...</div>
          )}

          <h3 className="text-lg font-bold mb-4 border-b border-white border-opacity-10 pb-2 mt-8" style={{ color: 'var(--color-gold)' }}>Metadata</h3>
          <div className="space-y-3 text-sm opacity-80">
            <div><span className="opacity-50 block text-xs">Collection</span> {item.collection}</div>
            <div><span className="opacity-50 block text-xs">Rights</span> {item.rights_status}</div>
          </div>
        </div>
      </div>
    </div>
  );
}

